Enable Centos8 compile / new boost version
New boost version changes API

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #!/bin/bash
 # Simple configuration script for people who expect such a script to exist.
-# Please do not convert istatd to autotools. We will likely not accept such 
+# Please do not convert istatd to autotools. We will likely not accept such
 # a conversion. Thanks for your interest in istatd, and good luck!
 
 set -e
@@ -10,7 +10,7 @@ rm -f makevars.config
 rm -f config.h
 
 # Find Python version 2.
-# If this fails, you need to create appropriate aliases or symlinks for 
+# If this fails, you need to create appropriate aliases or symlinks for
 # testing to work!
 /usr/bin/env python -V
 /usr/bin/env python2 -V
@@ -37,6 +37,7 @@ echo "# makevars.config for istatd generated on " `date` > makevars.config
 BOOST_SYSTEM=""
 BOOST_FILESYSTEM=""
 BOOST_THREAD=""
+BOOST_VERSION=""
 BOOST_IOSTREAMS=""
 STATGRAB=""
 LIBRT=""
@@ -58,6 +59,10 @@ while [ $# -gt 0 ]; do
         --boost_thread)
             shift
             BOOST_THREAD="$1"
+            ;;
+        --boost_version)
+            shift
+            BOOST_VERSION="$1"
             ;;
         --boost_iostreams)
             shift
@@ -163,6 +168,18 @@ if [ -z "$BOOST_THREAD" ]; then
     fi
 fi
 
+# hack to determine boost version
+if [ -z "$BOOST_VERSION" ]; then
+    BOOST_VERSION=$(echo -e '#include <boost/version.hpp>\nBOOST_VERSION' | gcc -x c++ -E -| tail -1)
+    if [ -z "$BOOST_VERSION" ]; then
+        echo "Cannot find boost version from boost/version.hpp"
+        echo "Ensure boost dev packages are installed or specify --boost_version"
+        echo "e.g. for 1.66 use --boost_version=106600"
+        exit 1
+    fi
+fi
+
+
 if [ -z "$BOOST_IOSTREAMS" ]; then
     BOOST_IOSTREAMS=`findone -lboost_iostreams -lboost_iostreams-mt`
     if [ -z "$BOOST_IOSTREAMS" ]; then
@@ -226,6 +243,7 @@ if [ ! -z "$ETC_PREFIX" ]; then
     echo "ETC_PREFIX=$ETC_PREFIX" >> makevars.config
 fi
 
+
 echo "checking for libstatgrab interface version"
 echo "/* config.h generated by configure script */" >> config.h
 echo "" >> config.h
@@ -241,6 +259,17 @@ else
     echo "found libstatgrab 0.17 interface"
     echo "#define LIBSTATGRAB_API_0_17" >> config.h
 fi
+
+if [ $BOOST_VERSION -gt 105300 ]; then
+    # use new strand stuff
+    echo "#define BOOST_NEW_STRAND" >> config.h
+    echo "#define BOOST_ASIO_STRAND boost::asio::io_context::strand" >> config.h
+    echo "#define BOOST_SYSTEM_CATEGORY boost::system::system_category" >> config.h
+else
+    echo "#define BOOST_ASIO_STRAND boost::asio::strand" >> config.h
+    echo "#define BOOST_SYSTEM_CATEGORY boost::system::get_system_category" >> config.h
+fi
+
 rm -rf tmp
 
 echo "All done"
